services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    env_file:
      - ./.env
    ports:
      - "${WEB_PORT:-3000}:3000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DIRECT_URL: "${DIRECT_URL}"
      UPSTASH_REDIS_URL: "${UPSTASH_REDIS_URL}"
      UPSTASH_REDIS_TOKEN: "${UPSTASH_REDIS_TOKEN}"
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000'
